---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
      username: ((docker_hub_username))
      password: ((docker_hub_authtoken))
resources:
  - name: git-main
    type: git
    icon: github-circle
    source:
      uri: https://github.com/alphagov/govuk-attribute-service-prototype.git
      branch: main

  - name: govuk-slack
    type: slack-notification
    source:
      url: https://hooks.slack.com/((slack_webhook_url))

  - name: git-main-gems-dockerfile
    icon: github-circle
    type: git
    source:
      uri: https://github.com/alphagov/govuk-attribute-service-prototype.git
      branch: main
      paths:
        - concourse/Dockerfile
        - Gemfile*

  - name: every-day
    type: time
    source:
      interval: 24h

  - name: tests-image
    type: docker-image
    icon: docker
    source:
      repository: ((readonly_private_ecr_repo_url))
      tag: govuk-attribute-service-tests-image

jobs:
  - name: update-pipeline
    plan:
      - get: git-main
        trigger: true
      - set_pipeline: govuk-attribute-service-prototype
        file: git-main/concourse/pipeline.yml

  - name: build-tests-image
    serial: true
    build_log_retention:
      builds: 100
    plan:
      - get: every-day
        trigger: true
      - get: git-main-gems-dockerfile
        trigger: true
      - put: tests-image
        params:
          build: git-main-gems-dockerfile
          dockerfile: git-main-gems-dockerfile/concourse/Dockerfile
        on_failure:
          put: govuk-slack
          params:
            channel: '#govuk-accounts-tech'
            username: 'Concourse (GOV.UK Accounts)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Test image build for the GOV.UK Attribute Service has failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: run-quality-checks
    serial: true
    plan:
      - get: tests-image
        passed:
          - build-tests-image
        trigger: true
      - get: git-main
        trigger: true
      - task: run-tests-task
        image: tests-image
        config:
          inputs:
            - name: git-main
          outputs:
            - name: committer-details
          platform: linux
          run:
            dir: git-main
            path: bash
            args:
              - -c
              - |
                set -eu
                service postgresql start
                su - postgres -c "psql -c \"create role root with createdb login password 'password';\""
                export TEST_DATABASE_URL="postgres://root:password@localhost:5432/accounts"
                bundle install
                bundle exec rails db:setup
                bundle exec rails db:migrate
                bundle exec rake
        on_failure:
          put: govuk-slack
          params:
            channel: '#govuk-accounts-tech'
            username: 'Concourse (GOV.UK Accounts)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Quality checks for the GOV.UK Attribute Service have failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: deploy-app-staging
    serial: true
    plan:
      - get: git-main
        trigger: true
        passed: [run-quality-checks]
      - task: deploy-to-paas
        file: git-main/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          ACCOUNT_MANAGER_TOKEN: ((account-manager-token-staging))
          CDN_DOMAIN: account.staging.publishing.service.gov.uk
          CF_SPACE: staging
        on_failure:
          put: govuk-slack
          params:
            channel: '#govuk-accounts-tech'
            username: 'Concourse (GOV.UK Accounts)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Staging deployment for the GOV.UK Attribute Service has failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: smoke-test-staging
    serial: true
    plan:
      - get: git-main
        trigger: true
        passed: [deploy-app-staging]
      - task: smoke-test
        file: git-main/concourse/tasks/smoke-test.yml
        timeout: 5m
        params:
          URL: 'https://attributes.account.staging.publishing.service.gov.uk'
          MESSAGE: "Checks that the application deployed to staging is not critically broken. If this fails, you should investigate immediately."
        on_failure:
          put: govuk-slack
          params:
            channel: '#govuk-accounts-tech'
            username: 'Concourse (GOV.UK Accounts)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Staging smoke tests for the GOV.UK Attribute Service have failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: deploy-app-production
    serial: true
    plan:
      - get: git-main
        trigger: true
        passed: [smoke-test-staging]
      - task: deploy-to-paas
        file: git-main/concourse/tasks/deploy-to-govuk-paas.yml
        params:
          ACCOUNT_MANAGER_TOKEN: ((account-manager-token-production))
          BIGQUERY_CREDENTIALS: ((bigquery-credentials-production))
          CDN_DOMAIN: account.publishing.service.gov.uk
          CF_SPACE: production
        on_failure:
          put: govuk-slack
          params:
            channel: '#govuk-accounts-tech'
            username: 'Concourse (GOV.UK Accounts)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Production deployment for the GOV.UK Attribute Service has failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

  - name: smoke-test-production
    serial: true
    plan:
      - get: git-main
        trigger: true
        passed: [deploy-app-production]
      - task: smoke-test
        file: git-main/concourse/tasks/smoke-test.yml
        timeout: 5m
        params:
          URL: 'https://attributes.account.publishing.service.gov.uk'
          MESSAGE: "Checks that the application deployed to production is not critically broken. If this fails, you should investigate immediately."
        on_failure:
          put: govuk-slack
          params:
            channel: '#govuk-accounts-tech'
            username: 'Concourse (GOV.UK Accounts)'
            icon_emoji: ':concourse:'
            silent: true
            text: |
              :kaboom:
              Production smoke tests for the GOV.UK Attribute Service have failed
              Failed build: http://cd.gds-reliability.engineering/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
