platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: 7a3a7f0c864b376bbf68304985124702f468944b
inputs:
  - name: git-main
    path: src
params:
  CF_API: https://api.london.cloud.service.gov.uk
  CF_APP_NAME: govuk-attribute-service
  CF_ORG: govuk-accounts
  CF_PASSWORD: ((paas-password))
  CF_STARTUP_TIMEOUT: 15 # minutes
  CF_USERNAME: ((paas-username))
  SENTRY_DSN: https://((sentry-dsn))
  WORKER_INSTANCES: 1

run:
  dir: src
  path: sh
  args:
    - "-c"
    - |
      set -eu
      cf api "$CF_API"
      cf auth
      cf t -o "$CF_ORG" -s "$CF_SPACE"
      cf create-app $CF_APP_NAME || true
      cf apply-manifest -f manifest.yml
      cf set-env $CF_APP_NAME CF_STARTUP_TIMEOUT "$CF_STARTUP_TIMEOUT"
      cf set-env $CF_APP_NAME ACCOUNT_MANAGER_TOKEN "$ACCOUNT_MANAGER_TOKEN"
      cf set-env $CF_APP_NAME ACCOUNT_MANAGER_URL "www.${CDN_DOMAIN}"

      cf attach-autoscaling-policy $CF_APP_NAME $CF_APP_SCALING_POLICY

      if [[ -n "${BIGQUERY_CREDENTIALS:-}" ]]; then
        cf set-env $CF_APP_NAME BIGQUERY_CREDENTIALS "$BIGQUERY_CREDENTIALS"
      fi

      cf set-env $CF_APP_NAME SENTRY_DSN "$SENTRY_DSN"
      cf set-env $CF_APP_NAME SENTRY_CURRENT_ENV "$CF_SPACE"

      cf push $CF_APP_NAME --strategy rolling
      cf map-route $CF_APP_NAME "$CDN_DOMAIN" --hostname attributes

      cf scale --process worker -i "$WORKER_INSTANCES" $CF_APP_NAME
